channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bokeh=2.4.3
  - dask=2022.10.0
  - geopandas=0.11.1
  - pandas=1.4.3
  - shapely=1.8.5
  - pip
  - pip:
      - -e .
      - requests==2.28.1
